services:
  app:
    container_name: places
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./directory-places:/app
    depends_on:
      - mongodb
      - mysql
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=breaze
      - MONGO_PASSWORD=12345678
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
    networks:
      - red_places_directory

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=breaze
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    volumes:
      - mongo_data:/data/db
    networks:
      - red_places_directory
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      retries: 5

  mysql:
    image: mysql:8.4.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - red_places_directory

volumes:
  mongo_data:
  mysql_data:

networks:
  red_places_directory:
